apiVersion: apps/v1
kind: Deployment
metadata:
  name: sit753-62hd-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sit753-62hd
  template:
    metadata:
      labels:
        app: sit753-62hd
    spec:
      containers:
        - name: sit753-62hd
          image: dushyantsapre1981/sit753_62hd:1.0.0-59
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
